-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2026-07-16T04:51:03.255Z

CREATE TYPE "role" AS ENUM (
  'BUYER',
  'SELLER'
);

CREATE TYPE "seller_type" AS ENUM (
  'INDIVIDUAL',
  'SOLE_PROPRIETOR',
  'CORPORATION'
);

CREATE TYPE "seller_status" AS ENUM (
  'ACTIVE',
  'SUSPENDED'
);

CREATE TYPE "product_status" AS ENUM (
  'ON_SALE',
  'OFF_SALE'
);

CREATE TYPE "order_status" AS ENUM (
  'PAID',
  'PARTIALLY_SHIPPED',
  'SHIPPED',
  'COMPLETED'
);

CREATE TYPE "payment_status" AS ENUM (
  'APPROVED',
  'REJECTED'
);

CREATE TYPE "reservation_status" AS ENUM (
  'HELD',
  'CONFIRMED',
  'RELEASED'
);

CREATE TYPE "delivery_status" AS ENUM (
  'PENDING',
  'SHIPPING',
  'DELIVERED'
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(100) NOT NULL,
  "display_name" varchar(50) NOT NULL,
  "created_at" timestamptz NOT NULL
);

CREATE TABLE "user_roles" (
  "user_id" bigint NOT NULL,
  "role" role NOT NULL,
  PRIMARY KEY ("user_id", "role")
);

CREATE TABLE "sellers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint UNIQUE NOT NULL,
  "seller_type" seller_type NOT NULL,
  "store_name" varchar(100) NOT NULL,
  "business_registration_number" varchar(20),
  "representative_name" varchar(50),
  "contact_phone" varchar(30),
  "contact_email" varchar(255),
  "status" seller_status NOT NULL DEFAULT 'ACTIVE',
  "created_at" timestamptz NOT NULL
);

CREATE TABLE "products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seller_id" bigint NOT NULL,
  "name" varchar(200) NOT NULL,
  "description" text,
  "price_krw" bigint NOT NULL,
  "stock" int NOT NULL,
  "reserved" int NOT NULL DEFAULT 0,
  "image_url" varchar(500),
  "status" product_status NOT NULL DEFAULT 'ON_SALE',
  "version" bigint NOT NULL DEFAULT 0
);

CREATE TABLE "carts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "buyer_id" bigint UNIQUE NOT NULL
);

CREATE TABLE "cart_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "quantity" int NOT NULL
);

CREATE TABLE "orders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "buyer_id" bigint NOT NULL,
  "total_krw" bigint NOT NULL,
  "ship_recipient" varchar(50) NOT NULL,
  "ship_address" varchar(300) NOT NULL,
  "ship_phone" varchar(30) NOT NULL,
  "status" order_status NOT NULL,
  "placed_at" timestamptz NOT NULL
);

CREATE TABLE "sub_orders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "seller_id" bigint NOT NULL,
  "subtotal_krw" bigint NOT NULL
);

CREATE TABLE "order_lines" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sub_order_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "product_name_snapshot" varchar(200) NOT NULL,
  "unit_price_krw_snapshot" bigint NOT NULL,
  "quantity" int NOT NULL
);

CREATE TABLE "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint NOT NULL,
  "idempotency_key" varchar(64) UNIQUE NOT NULL,
  "amount_krw" bigint NOT NULL,
  "status" payment_status NOT NULL,
  "gateway_ref" varchar(100),
  "created_at" timestamptz NOT NULL
);

CREATE TABLE "payment_idempotency" (
  "key" varchar(64) PRIMARY KEY,
  "request_hash" varchar(64) NOT NULL,
  "status" varchar(20) NOT NULL,
  "order_id" bigint,
  "created_at" timestamptz NOT NULL
);

CREATE TABLE "stock_reservations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "buyer_id" bigint NOT NULL,
  "quantity" int NOT NULL,
  "status" reservation_status NOT NULL DEFAULT 'HELD',
  "expires_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL
);

CREATE TABLE "deliveries" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sub_order_id" bigint UNIQUE NOT NULL,
  "status" delivery_status NOT NULL DEFAULT 'PENDING',
  "shipped_at" timestamptz,
  "delivered_at" timestamptz
);

CREATE INDEX ON "products" ("seller_id");

CREATE INDEX ON "products" ("status");

CREATE UNIQUE INDEX ON "cart_items" ("cart_id", "product_id");

CREATE INDEX ON "orders" ("buyer_id");

CREATE INDEX ON "sub_orders" ("order_id");

CREATE INDEX ON "sub_orders" ("seller_id");

CREATE INDEX ON "order_lines" ("sub_order_id");

CREATE INDEX ON "stock_reservations" ("status", "expires_at");

CREATE INDEX ON "stock_reservations" ("product_id");

COMMENT ON COLUMN "users"."password_hash" IS 'BCrypt 해시';

COMMENT ON TABLE "user_roles" IS 'User.roles(Set<Role>) 매핑 — 한 계정이 BUYER/SELLER 복수 보유(FR-004)';

COMMENT ON TABLE "sellers" IS 'sellerType != INDIVIDUAL 이면 사업자등록번호·대표자 필수 (ADR-0009)';

COMMENT ON COLUMN "sellers"."user_id" IS '1:1';

COMMENT ON COLUMN "sellers"."business_registration_number" IS '사업자·법인이면 필수, 형식·중복 검증';

COMMENT ON COLUMN "sellers"."representative_name" IS '사업자·법인이면 필수';

COMMENT ON COLUMN "products"."seller_id" IS '[cross-context] → sellers.id';

COMMENT ON COLUMN "products"."price_krw" IS '정수 원, >= 0';

COMMENT ON COLUMN "products"."stock" IS '>= 0';

COMMENT ON COLUMN "products"."reserved" IS '0 <= reserved <= stock (초과판매 0)';

COMMENT ON COLUMN "products"."version" IS '낙관적 버전(보조)';

COMMENT ON COLUMN "carts"."buyer_id" IS '[cross-context] → users.id (1인 1카트)';

COMMENT ON COLUMN "cart_items"."product_id" IS '[cross-context] → products.id';

COMMENT ON COLUMN "cart_items"."quantity" IS '>= 1';

COMMENT ON COLUMN "orders"."buyer_id" IS '[cross-context] → users.id';

COMMENT ON COLUMN "orders"."total_krw" IS '서버 산출 총액(정수 원)';

COMMENT ON COLUMN "orders"."status" IS 'Delivery 상태 집계';

COMMENT ON TABLE "sub_orders" IS '판매자별 정산·주문 단위(배송상태 없음). 배송은 deliveries가 담당(ADR-0008)';

COMMENT ON COLUMN "sub_orders"."seller_id" IS '[cross-context] → sellers.id';

COMMENT ON COLUMN "sub_orders"."subtotal_krw" IS '판매자별 소계 — 정산 기준';

COMMENT ON COLUMN "order_lines"."product_id" IS '[cross-context] → products.id';

COMMENT ON COLUMN "order_lines"."product_name_snapshot" IS '결제 시점 스냅샷(FR-023)';

COMMENT ON COLUMN "order_lines"."unit_price_krw_snapshot" IS '결제 시점 단가 스냅샷';

COMMENT ON COLUMN "order_lines"."quantity" IS '>= 1';

COMMENT ON COLUMN "payments"."order_id" IS '[cross-context] → orders.id';

COMMENT ON COLUMN "payments"."idempotency_key" IS '서버 발급 UUID';

COMMENT ON COLUMN "payments"."amount_krw" IS '서버 검증 금액';

COMMENT ON TABLE "payment_idempotency" IS '동일 키 재요청 시 기존 결과 반환 — 정확히 한 번(FR-018, SC-004)';

COMMENT ON COLUMN "payment_idempotency"."key" IS '멱등키(UUID)';

COMMENT ON COLUMN "payment_idempotency"."order_id" IS '[cross-context] 생성된 주문(있으면)';

COMMENT ON TABLE "stock_reservations" IS 'HELD→CONFIRMED/RELEASED. 만료 스윕이 HELD & expires_at<now 를 RELEASED (SC-005)';

COMMENT ON COLUMN "stock_reservations"."product_id" IS '[cross-context] → products.id';

COMMENT ON COLUMN "stock_reservations"."buyer_id" IS '[cross-context] → users.id';

COMMENT ON COLUMN "stock_reservations"."quantity" IS '>= 1';

COMMENT ON COLUMN "stock_reservations"."expires_at" IS '생성 + 10분(TTL)';

COMMENT ON TABLE "deliveries" IS '결제 완료 시 SubOrder마다 PENDING 생성. PENDING→SHIPPING→DELIVERED(FR-011)';

COMMENT ON COLUMN "deliveries"."sub_order_id" IS '[cross-context] → sub_orders.id (1:1)';

COMMENT ON COLUMN "deliveries"."delivered_at" IS '배송완료 시각 — 향후 정산 트리거';

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sellers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sub_orders" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_lines" ADD FOREIGN KEY ("sub_order_id") REFERENCES "sub_orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("idempotency_key") REFERENCES "payment_idempotency" ("key") DEFERRABLE INITIALLY IMMEDIATE;
