-- ShopFlow 초기 스키마 (V1)
-- 근거: data-model.md, erd.dbml. 검토 보고서 반영:
--   * enum은 varchar + CHECK (JPA @Enumerated(STRING) 매핑, T007)
--   * 무결성 CHECK 제약 추가 (reserved/stock/quantity/amount)
--   * ADR-0010 v2(단일 DB 확정)로 컨텍스트 간 FK도 물리 제약으로 둔다.

-- ===================== 계정 =====================
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    display_name  VARCHAR(50)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL
);

CREATE TABLE user_roles (
    user_id BIGINT      NOT NULL REFERENCES users (id),
    role    VARCHAR(20) NOT NULL CHECK (role IN ('BUYER', 'SELLER')),
    PRIMARY KEY (user_id, role)
);

CREATE TABLE sellers (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                      BIGINT       NOT NULL UNIQUE REFERENCES users (id),
    seller_type                  VARCHAR(20)  NOT NULL CHECK (seller_type IN ('INDIVIDUAL', 'SOLE_PROPRIETOR', 'CORPORATION')),
    store_name                   VARCHAR(100) NOT NULL,
    business_registration_number VARCHAR(20),
    representative_name          VARCHAR(50),
    contact_phone                VARCHAR(30),
    contact_email                VARCHAR(255),
    status                       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SUSPENDED')),
    created_at                   TIMESTAMPTZ  NOT NULL,
    -- 사업자·법인이면 사업자등록번호·대표자 필수 (ADR-0009)
    CONSTRAINT chk_seller_business CHECK (
        seller_type = 'INDIVIDUAL'
        OR (business_registration_number IS NOT NULL AND representative_name IS NOT NULL)
    )
);

-- ===================== 상품 =====================
CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id   BIGINT       NOT NULL REFERENCES sellers (id),
    name        VARCHAR(200) NOT NULL,
    description TEXT,
    price_krw   BIGINT       NOT NULL CHECK (price_krw >= 0),
    stock       INT          NOT NULL CHECK (stock >= 0),
    reserved    INT          NOT NULL DEFAULT 0,
    image_url   VARCHAR(500),
    status      VARCHAR(20)  NOT NULL DEFAULT 'ON_SALE' CHECK (status IN ('ON_SALE', 'OFF_SALE')),
    version     BIGINT       NOT NULL DEFAULT 0,
    -- 초과판매 불변식의 최후 방어선 (검토 보고서 #10/#19)
    CONSTRAINT chk_reserved_range CHECK (reserved >= 0 AND reserved <= stock)
);
CREATE INDEX idx_products_seller ON products (seller_id);
CREATE INDEX idx_products_status ON products (status);

-- ===================== 주문(장바구니 포함) =====================
CREATE TABLE carts (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL UNIQUE REFERENCES users (id)
);

CREATE TABLE cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT NOT NULL REFERENCES carts (id),
    product_id BIGINT NOT NULL REFERENCES products (id),
    quantity   INT    NOT NULL CHECK (quantity >= 1),
    UNIQUE (cart_id, product_id)
);

CREATE TABLE orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id      BIGINT       NOT NULL REFERENCES users (id),
    total_krw     BIGINT       NOT NULL CHECK (total_krw >= 0),
    ship_recipient VARCHAR(50) NOT NULL,
    ship_address  VARCHAR(300) NOT NULL,
    ship_phone    VARCHAR(30)  NOT NULL,
    status        VARCHAR(20)  NOT NULL CHECK (status IN ('PAID', 'PARTIALLY_SHIPPED', 'SHIPPED', 'COMPLETED')),
    placed_at     TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_orders_buyer ON orders (buyer_id);

CREATE TABLE sub_orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT NOT NULL REFERENCES orders (id),
    seller_id    BIGINT NOT NULL REFERENCES sellers (id),
    seller_store_name_snapshot VARCHAR(100) NOT NULL,
    subtotal_krw BIGINT NOT NULL CHECK (subtotal_krw >= 0)
);
CREATE INDEX idx_sub_orders_order ON sub_orders (order_id);
CREATE INDEX idx_sub_orders_seller ON sub_orders (seller_id);

CREATE TABLE order_lines (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_order_id            BIGINT       NOT NULL REFERENCES sub_orders (id),
    product_id              BIGINT       NOT NULL REFERENCES products (id),
    product_name_snapshot   VARCHAR(200) NOT NULL,
    unit_price_krw_snapshot BIGINT       NOT NULL CHECK (unit_price_krw_snapshot >= 0),
    quantity                INT          NOT NULL CHECK (quantity >= 1)
);
CREATE INDEX idx_order_lines_sub_order ON order_lines (sub_order_id);

-- ===================== 결제 =====================
CREATE TABLE payment_idempotency (
    key          VARCHAR(64) PRIMARY KEY,
    request_hash VARCHAR(64) NOT NULL,
    status       VARCHAR(20) NOT NULL CHECK (status IN ('STARTED', 'DONE', 'FAILED')),
    order_id     BIGINT,
    created_at   TIMESTAMPTZ NOT NULL
);

CREATE TABLE payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT,  -- nullable: 실패 결제도 기록 (검토 보고서 #5)
    idempotency_key VARCHAR(64) NOT NULL UNIQUE REFERENCES payment_idempotency (key),
    amount_krw      BIGINT      NOT NULL CHECK (amount_krw >= 0),
    status          VARCHAR(20) NOT NULL CHECK (status IN ('APPROVED', 'REJECTED')),
    gateway_ref     VARCHAR(100),
    created_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_payments_order ON payments (order_id);

-- payment_idempotency.order_id → orders (결제 컨텍스트 → 주문 컨텍스트)
ALTER TABLE payment_idempotency ADD CONSTRAINT fk_pi_order FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE payments ADD CONSTRAINT fk_pay_order FOREIGN KEY (order_id) REFERENCES orders (id);

-- ===================== 재고 =====================
CREATE TABLE stock_reservations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT      NOT NULL REFERENCES products (id),
    buyer_id   BIGINT      NOT NULL REFERENCES users (id),
    quantity   INT         NOT NULL CHECK (quantity >= 1),
    status     VARCHAR(20) NOT NULL DEFAULT 'HELD' CHECK (status IN ('HELD', 'CONFIRMED', 'RELEASED')),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_reservations_sweep ON stock_reservations (status, expires_at);
CREATE INDEX idx_reservations_product ON stock_reservations (product_id);

-- ===================== 배송 =====================
CREATE TABLE deliveries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_order_id BIGINT      NOT NULL UNIQUE REFERENCES sub_orders (id),
    status       VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SHIPPING', 'DELIVERED')),
    shipped_at   TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ
);
